name: outputs-practice

on: push

jobs:

  test:
    runs-on: ubuntu-slim

    outputs:
      app_version: ${{ steps.version.outputs.version }}

    steps:
      - name: app_version
        id: version
        run: echo "version=2.5" >> "$GITHUB_OUTPUT"

  security:
    needs: test
    runs-on: ubuntu-slim

    steps:
      - name: print version
        run: echo "Testing version: ${{ needs.test.outputs.app_version }}"
