name: Practice

on:
  push

jobs:
  test:
    runs-on: ubuntu-slim

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: print msg
        run: echo "Running tests"

        
  security:
    runs-on: ubuntu-slim
    needs: test

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: print msg
        run: echo "Running security scans"
        
