name: outputs-practice

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      app_version: ${{ steps.version.outputs.app_version }}

    steps:
      - name: app_version
        id: version
        run: echo "app_version=2.5" >> "$GITHUB_OUTPUT"

  security:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: print version
        run: echo "Testing version: ${{ needs.test.outputs.app_version }}"
